import numpy as np
import matplotlib.pyplot as plt
import re
import math

# === 1. METNİ BURAYA YAPIŞTIR ===
text = """BukitapgerçeklereveolaylarailişkinbiraçıklamaolmaiddiasındadeğildirmilyonlarcatutuklununtekrartekraryaşadığıkişiseldeneyimlerinbirözetidirBubirtoplamakampınınoradabulunupdasağkurtulmayıbaşaranlardanbirisitarafındananlatılaniçöyküsüdürBuöykününkonusuzatenyeterinceanlatılanyinedeyeterinceinanılmayanbüyükdehşetlerdeğilyaşanansayısızküçükacılardırBaşkabirdeyişlebukitapşusoruyacevapvermeyeçalışacakOrtalamabirtutuklununzihnindecanlandığışekildebirtoplamakampındakigündelikyaşamnasılbirşeydiBuradaanlatılanolaylarınçoğubüyükveünlütoplamakamplarındadeğilgerçekimhaişlemlerininçoğunluğunungerçekleştiğiküçükkamplardageçmiştirBuöykübüyükkahramanlarınyadaşehitlerinacılarımveölümlerinianlatmadığıgibiKapolarmyadaünlütutuklulannöyküsüdedeğildirBunedenlegüçlüolanınacılarımdeğilkayıtlarageçmeyenobüyükadsızkurbanlarordusununözverileriniçarmıhagerilişleriniveölümlerinikonuolarakseçmiştirBuordukollarındahiçbirayırdediciişarettaşımayanveKapolartarafındangerçektenküçümsenensıradantutuklulardanoluşmaktaydıBusıradantutuklularınyiyecekhemenhiçbirşeyleriolmamasınakarşınKapolarhiçbirzamanaçkalmamıştıraslındaKapolardanbirçoğutoplamakamplarındayaşamlarınınöncekidönemlerindeolduğundandahaiyibiryaşamsürmüştürÇoğunluklatutuklularakarşıgardiyanlardandahakatıdavranıyorlarvetutuklulanSSadamlarındandahaacımasızcadövüyorlardıBuKapolarelbettekişiliğiböylebirişeuygunolantutuklulararasındanseçiliyorvekendilerindenbekleneniyapmadıklarıtakdirdeanındagörevdenalmıyorlardıBuinsanlarınKapoyetkisinialıralmazSSadamlarındanvekampmuhafızlarındanhiçbirfarklarıkalmıyordubunedenlebenzerbirpsikolojiktemeldeyargılanabilirlerDışarıdanbakanbirisiiçinkampyaşamınailişkinduygusallıkveacımaylakarışıkyanlışbirfikiredinmekkolaydırçünkütutuklulararasındaegemenolançetinvarolmasavaşıkonusundapekbirşeybilmezBugündelikekmekiçinyaşamınkendisiiçinkişininkendiyaşamıyadaiyibirdostunyaşamıiçinverilenamansızbirmücadeleydiResmikaynaklarcabellisayıdatutuklununbaşkabirkampanakliolarakaçıklananbirsevkolayınıelealalımoysagerçektebuşevkinnihaivanşyeriningazodalarıolduğunutahminetmekhiçdezordeğildiÇalışamayacakkadarhastayadazayıfolantutuklulargazodalarıvekrematoryumlarbulunanküçükmerkezitoplamakamplarındanbirisinegönderiliyorduGidecekleribelirlemekiçinyapılanseçmeişlemibütüntutuklularyadagruplararasındaamansızbirmücadeleişaretioluyorduÖnemliolantekşeykişininkendiadınınvearkadaşınınadınınkurbanlarlistesindeatlanmasıydıbunakarşınherkeskurtanlanherinsaniçinbirbaşkakurbanınbulunmasıgerektiğinidebiliyorduHersevkiyattabellisayıdatutuklunungitmesigerekiyorduKimingideceğigerçektenbirönemarzetmiyorduçünkütutuklulardanherbirisibirnumaradanbaşkabirşeydeğildiToplamakampınagirişlerindebütünbelgelerivebütüneşyalarıalınıyorduenazındanAuschwitzToplamaKampındakiyöntembuyduBunedenlehertutuklusahtebirisimvemeslekuydurmafırsatınasahiptiveçeşitlinedenlerdenötürübirçoğubunuyapıyorduYetkililerinilgilendiğitekşeytutuklulannnumaralanydıBunumaralarçoğunluklavücudadövmeyleyazılıyorayncagiysilerinüzerinedeyazılmasıgerekiyorduBirtutukluhakkındaihbardabulunmakisteyenbirgardiyanıntutuklununnumarasınabakmasıyeterliydiböylebakışlardannekadarkorkardıkbuamaçlakesinlikletutukluyaadınısormazdıSevkiçinhareketetmeküzereolankonvoyadönecekolursakkimseninahlâkisorunlarakafayormayanezamanınedearzusuvardıHerkesindüşündüğütekbirşeydiEvindekendisinibekleyenailesiiçinyaşamakvearkadaşlannıkurtarmakBunedenlebirbaşkatutuklununbirbaşkanumaranınsevkıyattakendiyerinialmasıiçinelindengeleniyapmaktabiranbileduraksamıyorduDahaöncedeğindiğimgibiKaposeçmeişleminegatifbirşeyditutuklulariçindeenacımasızenhayvaniolanlarbuişiçinseçiliyorduancakbazımutlulukvericiistisnalardavardıAmaSSlertarafındanyürütülenKaposeçimininyanısırabütüntutuklulararasındaherzamansürüpgidenbirkendindenseçilmesüreciişliyorduOrtalamaolaraksadeceyıllarboyuncaokamptanbukampataşmanvaroluşmücadelesindebütünahlâkdeğerlerinikaybedentutuklularyaşayabiliyorduBututuklularkendilerinikurtarmakiçindürüstolsunolmasınheryolahertürlüacımasızgücehırsızlığadostlarınaihanetebaşvurmayahazırlardıBirçokşanslıolayınyadamucizeninartıkbunanedersenizdeyinyardımıylageridönmeyibaşaranbizlerbiliyoruzEniyilerimizdönmediToplamakamplannailişkinbirçokaçıklamaolaykayıtlarazatengeçmişbulunmaktadırBuradaolaylarsadecebirinsanındeneyimlerininbirparçasıolduğuölçüdeanlamlıolacaktırAşağıdakidenemeninbetimlemeyeçalışacağışeydeiştebudeneyimlerinkesinyapısıdırBukamplardanbirisindekalmışolanlariçinkitaporadayaşananlarıgünümüzünbilgileriışığıaltındaaçıklamayaçalışacaktırHiçbirzamanböylebirdeneyimiyaşamamışolanlaraçısındanisekamplardansağçıkmayıbaşaranveşimdiyaşamıçokzorbulanazsayıdakitutuklunundeneyimlerininkavranmasınahiçdeğilseanlaşılmasınayardımcıolabilirBirzamanlartutukluolanbuinsanlarsıksıkşunusöylerYaşadıklarımızhakkındakonuşmayısevmiyoruzOnlanyaşamışolanlarınhiçbiraçıklamayaihtiyacıyokOolaylarıyaşamayanlariseneozamanhissettiklerimizinedeşimdihissettiklerimizianlayabilirPsikolojininbellibirbilimselnesnelcilikgerektirmesinedeniylekonuyuyöntemlibirşekildesunmakoldukçazorAmagözlemlerinikendisidebirtutukluykenyapmışolanbirinsangereklinesnelciliğetarafsızlığasahipolabilirmiDışandakibirisiböylebirnesnelciliğesahipolabiliramagerçekdeğeresahipifadelerdençokuzakolacaktırSadeceiçindeolanbilirYargılarındanesnelolmayabilirdeğerlendirmeleriorantısızolabilirBukaçınılmazKişiselönyargıdankaçınmakgerekirbukitabınkarşıkarşıyabulunduğugerçekzorlukdaiştebudurZamanzamançoközeldeneyimlerianlatacakcesaretesahipolmakgerekecekBukitabıisimsizanonimolarakyazmayıamaçlıyordumkitaptasadecekamptaverilennumaramıkullanacaktımAmametintamamlanıncakitabınisimsizbiryayınolarakdeğerininyansınıkaybedeceğiniveinançlanmıaçıkçadilegetirmecesaretinesahipolmamgerektiğinianladımBunedenleteşhirciliğekarşıyoğunbirtiksintiduymamarağmenkitaptakipasajlardanherhangibirisiniiptaletmeyekalkışmadımBukitaptaanlatılanlardankuruteorilerdamıtmayıbaşkalannabırakıyorumBuradaanlatılanlarBirinciDünyaSavaşındansonraaraştırmakonusuolanvedikenlitelhastalığısendromuylatanışmamızısağlayancezaeviyaşamıpsikolojisinekatkıdabulunabilirLeBonunbirkitabındakiçokiyibilinenbirdeyişibirazdeğiştirerekanacakolursamkitlelerinpsikopatolojisineilişkinbilgimizdekiderinleşmeyiİkinciDünyaSavaşınaborçluyuzçünkübusavaşbizesinirsavaşınıvetoplamakamplannıkazandırdıBuöyküsıradanbirtutukluolarakbenimkendideneyimlerimikonuettiğiiçinsonbirkaçhaftasıhariçkamptabirpsikiyatristyadadoktorolarakgörevyapmadığımıgururduyarakbelirtmekbenimaçımdanönemliMeslektaşlarımdanbirkaçıatıkkâğıtparçalanndanbandajolarakyararlanılanyetersizısıtmalıilkyardımistasyonlanndaçalışacakkadarşanslıydıAmaben90NumaraydımvezamanımınçoğunudemiryoluhatlarıiçinkazıyaparakveraydöşeyerekgeçiriyordumBirkeresindeişimsuşebekesiiçinbiryolunaltındatekbaşımabirtünelkazmaktıBuişödülsüzkalmamıştı9NoelindenhemenöncebeniprimkuponudenilenbirarmağanlaödüllendirdilerBukuponlarpratikanlamdaköleolaraksatıldığımızinşaatfirmasıtarafındandüzenleniyorduFirmahergüniçinhertutuklubaşınabelirlenensabitbirücretikampyetkililerineödüyorduBukuponlarfirmayaellipeniyemaloluyorduvetanesialtıadetsigarayladeğiştirilebiliyorduancakçoğudurumdakarşılığıhaftalarsonraalınabiliyorduvebazendegeçerliliksüreleridoluyorduOnikisigarakarşılığıbirödülüngururlusahibiolmuştumAmadahadaönemlisisigaralarınonikiçorbayladeğiştirilebilmesiydionikiçorbaiseçoğudurumdaaçlıkkarşısındagerçekbirgüvenceyekarşılıkgeliyorduGerçektesigaraiçmeayrıcalığıhaftalıkbirkuponkotasınasahipKapolarayadaantrepoveyaatölyedeustaolarakçalışanveyaptıklarıtehlikeliişlerkarşılığındabirkaçsigaraalantutuklularaaittiBunatekistisnayaşamairadesinikaybedenvesongünlerinintadınıçıkarmakisteyentutuklulardıDolayısıylakampsakinlerindenbirisininkendisigarasınıiçtiğinigördüğümüzzamandevametmedirencineolaninancınıkaybettiğinianlardıkvebirkezkaybedilinceyaşamairadesibirdahakolaykolaykazanılamıyorduBirçoktutuklunungözlemlerininvedeneyimlerininsonucuolarakortayaçıkanbüyükmiktarlardakimalzemeincelendiğizamankampsakinlerininkampyaşamınayönelikruhsaltepkilerininüçevresiaçıklıkkazanırKampaalınışınıizleyendönemkamprutinineçokiyiuyumsağladığıdönemveserbestbırakılışınıizleyendönemBirincievreyetipikolanbelirtisemptomşoktepkisidirBazıdurumlardatutuklununkamparesmenalınışındanöncebileşokortayaçıkabilirKampaalmışımailişkinkendideneyimimibirörnekolarakvereceğimBinbeşyüzkişidenoluşanbirgrupbirkaçgündürtrenlearalıksızseyahatediyorduHervagondaseksenkişivardıHerkeskendibagajınıngerikalanbirkaçkişideözeleşyalarınınüzerineuzanmakzorundaydıVagonlaröylesinetıkabasadoluydukisabahınilkışıklanancakpencerelerinüstkısımlanndaniçerisızabiliyorduHerkestrenincebriişgücüolarakçalıştınlacağımızbirmühimmatfabrikasınagitmesinibekliyorduHâlâSilesiadamıolduğumuzuyoksaPolonyayamıgirdiğimizibilmiyordukTrenindüdüğününyokoluşataşıdığıumutsuzyükiçinhavayayayılanacımadolubirimdatçığlığınıandıranesrarengizbirsesivardıDerkentreninhızıkesildibiranaistasyonayaklaştığımızanlaşılıyorduAnsızınkaygılıyolculannarasındanbirnidayükseldiBirişaretvarAuschwitzOandaherkesinkalbiduracakgibiolmuştuAuschwitzadıdehşetvericiolanherşeyekarşılıkgeliyorduGazodalankrematoryumlarölüyakmaodalankatliamlarTrensankitereddütedercesinesankiyolculannıoürkütücükavrayıştanolabildiğinceuzunbirsürekorumakistercesineağırağıryolunadevametti."""

# === 2. SESLİ / SESSİZ ===
vowels = "aeıioöuüAEIİOÖUÜ"
def is_vowel(ch): return ch in vowels

clean = re.sub(r"[^a-zA-ZçğıöşüÇĞİÖŞÜ]", "", text)

# === 3. SESLİ–SESSİZ SAYILARI ===
num_vowels = sum(1 for ch in clean if is_vowel(ch))
num_cons   = sum(1 for ch in clean if not is_vowel(ch))
total_chars = len(clean)

ratio_v = num_vowels / total_chars * 100
ratio_c = num_cons / total_chars * 100

print("=== HARF SAYILARI ===")
print(f"Sesli (Vowel)   : {num_vowels} (%{ratio_v:.2f})")
print(f"Sessiz (Cons.)  : {num_cons}   (%{ratio_c:.2f})")
print(f"Toplam Harf     : {total_chars}\n")

# === 4. GEÇİŞ SAYILARI ===
VV = VC = CV = CC = 0
for i in range(len(clean)-1):
    a, b = clean[i], clean[i+1]
    if is_vowel(a) and is_vowel(b): VV += 1
    elif is_vowel(a) and not is_vowel(b): VC += 1
    elif not is_vowel(a) and is_vowel(b): CV += 1
    else: CC += 1

total_trans = VV + VC + CV + CC

print("=== GEÇİŞ SAYILARI ===")
print(f"V → V : {VV}")
print(f"V → C : {VC}")
print(f"C → V : {CV}")
print(f"C → C : {CC}")
print(f"Toplam geçiş : {total_trans}\n")

# === 5. GEÇİŞ OLASILIK MATRİSİ ===
P = np.array([[VV, VC],
              [CV, CC]], dtype=float)
P = P / P.sum(axis=1, keepdims=True)

print("=== GEÇİŞ OLASILIK MATRİSİ P ===")
print("      V         C")
print(f"V [ {P[0,0]:.4f}   {P[0,1]:.4f} ]")
print(f"C [ {P[1,0]:.4f}   {P[1,1]:.4f} ]\n")

# === 6. BOX–MULLER NORMAL SAYI ÜRETİMİ ===
def box_muller(n):
    out = []
    while len(out) < n:
        u1, u2 = np.random.rand(), np.random.rand()
        if u1 == 0: continue
        r = math.sqrt(-2*math.log(u1))
        t = 2*math.pi*u2
        out.append(r*math.cos(t))
        if len(out) < n:
            out.append(r*math.sin(t))
    return np.array(out)

def normal_to_uniform(z):
    return 0.5*(1 + np.vectorize(math.erf)(z/np.sqrt(2)))

# === 7. MARKOV SİMÜLASYONU ===
sim_len = 10000
z_vals = box_muller(sim_len*5)
u_vals = normal_to_uniform(z_vals)
idx = 0

current = 'V' if u_vals[idx] < 0.5 else 'C'
idx += 1

sim = [current]
for _ in range(sim_len-1):
    r = u_vals[idx]
    idx += 1
    if current == 'V': current = 'V' if r < P[0,0] else 'C'
    else: current = 'V' if r < P[1,0] else 'C'
    sim.append(current)

pV = sim.count('V') / sim_len
pC = sim.count('C') / sim_len

print("=== SİMÜLASYON ORANLARI ===")
print(f"sim(V) = {pV:.4f}")
print(f"sim(C) = {pC:.4f}\n")

